apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: app-dev
  name: arnab15-eastus-cloudapp-azure-com-cert-staging
spec:
  secretName: arnab15-eastus-cloudapp-azure-com-staging
  dnsNames:
  - arnab15.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - arnab15.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  